### ISSUE TITLE
Steps to get the project up and running on IIS Express

### ISSUE THREAD

**Issue by VarinderS** [Kentico/dancing-goat-mvc#1]
Hi Guys,

Just cloned this repository below are the steps I followed:
- Restore nuget packages
- Manually added missing CMS.* references from some other kentico 8 project

How can I resolve ```CMS.ContinuousIntegration``` and ```CMS.ModuleUsageTracking``` references?

On building the project I'm facing below issues

Description | File | Line | Column | Project
-------------- | ----- | ----- | ---------- | --------
The type or namespace name 'Attachment' could not be found (are you missing a using directive or an assembly reference?) | MvcDemo.Web\Models\Cafes\CafeModel.cs | 9 | 16 | MvcDemo.Web
The type or namespace name 'DatabaseIDFieldAttribute' could not be found (are you missing a using directive or an assembly reference?) | MvcDemo.Web\Models\Generated\Pages\SocialLink.generated.cs | 51 | 4 | MvcDemo.Web
'Kentico.Web.Mvc.UrlHelperAttachmentMethods.Attachment()' is a 'method' but is used like a 'type' |	Kentico.Web.Mvc\UrlHelperAttachmentMethods.cs | 24 | 82 | Kentico.Web.Mvc

Above to errors are pretty much on all of the below files:
- CafeModel.cs
- SocialLink.generated.cs
- Contact.generated.cs
- Article.generated.cs
- AboutUsSection.generated.cs
- UrlHelperAttachmentMethod.cs
- SearchResultItem.cs

**Comment by ondrejsevcik** [comment]
Hi Varinder, 

this MVC example is for next version of Kentico. We will add this information into the repository description. I apologize for the misunderstanding.

**Comment by VarinderS** [comment]
Hi Ondrejsevcik,

Thanks for clarifying. I wonder if there's a way to jimmy this project to run on Kentico 8?

I've replaced all the ```Attachment``` references to ```AttachmentInfo``` and changed ```[DatabaseIDField]``` attribute to ```[DatabaseField]```

Commented out some code that was calling ```Services<ISubscriptionService>``` in ```NewsletterSubsucriptionService.cs```

Unloaded ```Kentico.Web.Mvc.Tests``` and ```MvcDemo.Web.Tests``` I'm guessing they require ```CMS.Tests``` namespace which could be in Kentico9

Above changes (Along with some other minor ones that I can't remember) made the ```Kentico.Mvc.Web``` and ```MvcDemo.Web``` projects to build successfully.

Now, The default route in ```MvcDemo.Web``` (```App_Start\RouteConfig.cs```)  is creating a culture constraint for a site with code name ```TestMvcDemo```

    var route = routes.MapRoute(
                          name: "Default",
                          url: "{culture}/{controller}/{action}/{id}",
                          defaults: new { culture = defaultCulture.Name, controller = "Home", action = "Index", id = UrlParameter.Optional },
                          constraints: new { culture = new SiteCultureConstraint("TestMvcDemo") }
                        );

Which is making code in ```SiteCultureConstraint.cs``` go belly up:

    public SiteCultureConstraint(string siteName)
    {
        // This guy is null
        var siteCultureNames = CultureSiteInfoProvider.GetSiteCultureCodes(siteName); 

        // This thing goes all ape shit because siteCultureNames is null :cry: 
        allowedCultureNames = new HashSet<string>(siteCultureNames, StringComparer.InvariantCultureIgnoreCase); 
    }


So: Is there a way to get hold of the database that contains ```TestMvcDemo``` Site? I'll give you some :cookie: :cookie: :cookie:

Thanks.

**Comment by petrsvihlik** [comment]
Hi @VarinderS 
thanks for your interest! Unfortunately, connecting the goat-mvc site to Kentico 8 would really be no use because it relies on some new concepts that will be introduced in version 9. To give you an example - any requests for files wouldn't work because in version 8 files (attachments/cms.files or any kind of resources like stylesheets...) are handled using GetFile.aspx/GetResource.ashx whereas in version 9 they've been converted to HTTP handlers and their routes can now be part of the MVC application. It would be best if you could wait a few weeks until we publish the RTM of Kentico 9. In the meantime, we can do a quick call where I can show you the wonders of MVC development in the upcoming version. Or perhaps we'll figure out something else. :) Just send me a message (on Twitter) if you're interested...

**Comment by VarinderS** [comment]
Hi petrsvihlik,

Thanks, Yeah, It'll be great to have a quick screen share session.

Let me know what is the best time to contact and how to contact
